GradleJobDslPluginException: Do not extend GradleExtension
Extend RuntimeException instead, because the JavaExec tasks run in the
scope of the normal project dependencies, not the buildscript
dependencies. Otherwise it would be necessary to define Gradle as a
dependency in projects using this plugin.

Change-Id: Ife6c446a24853e6ecf530ab4016c37d130ae966c